TARGET = lte_virtual_srio_module
OBJS =  fsmcore.o sriofsm.o virtual_srio.o riodt.o queue.o


EXTRA_CFLAGS += -w #avoid printing warning information
CURRENT = $(shell uname -r)
#KDIR = /lib/modules/$(CURRENT)/build
KDIR = /home/redhat/Desktop/amc718_bsp_source_release3/kernel/linux-2.6.34.6
#This is the kernel of Fedora18.
 
#KDIR = /home/fedora/QorIQ-SDK-V1.3.2-20130325-yocto/amc718/kernel
#This is the kernel of AMC719


PWD = $(shell pwd)

obj-m      := $(TARGET).o

$(TARGET)-objs := $(OBJS)

default:
	make -C $(KDIR) M=$(PWD) modules ARCH=powerpc CROSS_COMPILE=/opt/freescale/usr/local/gcc-4.5.55-eglibc-2.11.55/powerpc-linux-gnu/bin/powerpc-linux-gnu-
clean:
	-rm -f *.o *.ko .*.cmd .*.flags *.mod.c *~ core .depend .tmp_versions

depend .depend dep:
	$(CC) $(CFLAGS) -M *.c > .depend


ifeq (.depend,$(wildcard .depend))
include .depend
endif

